import copy
import random


class GreedyAgent:

  @staticmethod
  def select_best_move(sim):
    """Evaluates ALL available legal move combinations for ALL valid pairs in the turn,

    simulates each combination in an isolated sandbox board copy, and picks
    the move sequence that yields the HIGHEST immediate net score differential.
    """
    current_p = sim.current_player
    opp_p = "p2" if current_p == "p1" else "p1"

    valid_pairs = sim.board.activePairs(current_p)
    if not valid_pairs:
      return None, None, None

    best_candidates = []
    max_net_gain = -float("inf")

    # Baseline scores before taking a turn
    base_my_score = sim.scores[current_p]
    base_opp_score = sim.scores[opp_p]

    for pair in valid_pairs:
      pid1, pid2 = pair[0], pair[1]

      # 1. Get valid moves for Piece 1
      p1_moves = sim.board.get_valid_moves_for_piece(pid1, pid2, current_p)

      for mr1, mc1 in p1_moves:
        # 2. Temporarily apply Piece 1 move to get valid moves for Piece 2
        coords_dict = (
            sim.board.p1_pieces_coords
            if current_p == "p1"
            else sim.board.p2_pieces_coords
        )
        orig_r1, orig_c1 = coords_dict[pid1]

        sim.board.grid[orig_r1][orig_c1] = 0
        sim.board.grid[mr1][mc1] = pid1
        coords_dict[pid1] = (mr1, mc1)

        p2_moves = sim.board.get_valid_moves_for_piece(pid2, None, current_p)

        # Revert temporary move so engine state stays clean
        sim.board.grid[mr1][mc1] = 0
        sim.board.grid[orig_r1][orig_c1] = pid1
        coords_dict[pid1] = (orig_r1, orig_c1)

        for mr2, mc2 in p2_moves:
          # --- SANDBOX SIMULATION ---
          # Deepcopy simulation to evaluate full turn execution with zero side-effects
          sim_copy = copy.deepcopy(sim)

          # Force engine to execute this exact candidate move sequence
          sim_copy.execute_turn(pair, (mr1, mc1), (mr2, mc2))

          # Calculate exact score delta generated by this specific turn
          new_my_score = sim_copy.scores[current_p]
          new_opp_score = sim_copy.scores[opp_p]

          net_gain = (new_my_score - base_my_score) - (
              new_opp_score - base_opp_score
          )

          candidate = (pair, (mr1, mc1), (mr2, mc2))

          if net_gain > max_net_gain:
            max_net_gain = net_gain
            best_candidates = [candidate]
          elif net_gain == max_net_gain:
            best_candidates.append(candidate)

    # Pick randomly among moves tied for the maximum net score gain
    return (
        random.choice(best_candidates) if best_candidates else (pair, None, None)
    )